using UnityEngine;
using System.Collections.Generic;
using Fusion;

public class NetworkedMazeManager : NetworkBehaviour
{
    [SerializeField] private GameObject mazeCellPrefab, mazeCellprefabSmall, triggerPrefab;
    [SerializeField] private NetworkPrefabRef playerPrefab; // Drag your networked player prefab here
    [SerializeField] private int maze_x_size = 10, maze_z_size = 10;

    [Networked] public Vector2Int StartCell { get; set; }
    [Networked] public Vector2Int EndCell { get; set; }
    [Networked] public int MazeSeed { get; set; }
    [Networked] public bool MazeGenerated { get; set; }

    private MazeCell[,] mazeCells;
    private Dictionary<PlayerRef, NetworkObject> spawnedPlayers = new Dictionary<PlayerRef, NetworkObject>();

    public int MazeXSize => maze_x_size;
    public int MazeZSize => maze_z_size;

    public override void Spawned()
    {
        if (Object.HasStateAuthority)
        {
            // Host generates maze parameters
            MazeSeed = UnityEngine.Random.Range(int.MinValue, int.MaxValue);
            GenerateNetworkedMaze();
            MazeGenerated = true;
        }
    }

    public override void FixedUpdateNetwork()
    {
        // Clients wait for maze to be generated by host
        if (!Object.HasStateAuthority && MazeGenerated && mazeCells == null)
        {
            GenerateNetworkedMaze();
        }
    }

    [Rpc(RpcSources.StateAuthority, RpcTargets.All)]
    public void RPC_RegenerateMaze(int newSeed, int sizeX, int sizeZ)
    {
        MazeSeed = newSeed;
        maze_x_size = sizeX;
        maze_z_size = sizeZ;
        GenerateNetworkedMaze();
    }

    public void SetMazeSize(int x, int z)
    {
        maze_x_size = x;
        maze_z_size = z;
    }

    public void GenerateMazePublic()
    {
        if (Object.HasStateAuthority)
        {
            int newSeed = UnityEngine.Random.Range(int.MinValue, int.MaxValue);
            RPC_RegenerateMaze(newSeed, maze_x_size, maze_z_size);
        }
    }

    private void GenerateNetworkedMaze()
    {
        // Use networked seed for consistent generation across all clients
        UnityEngine.Random.State oldState = UnityEngine.Random.state;
        UnityEngine.Random.InitState(MazeSeed);

        // Clear old maze
        if (mazeCells != null)
        {
            foreach (var cell in mazeCells)
            {
                if (cell != null)
                    Destroy(cell.gameObject);
            }
        }

        mazeCells = new MazeCell[maze_x_size, maze_z_size];
        GenerateMaze();

        // Restore random state
        UnityEngine.Random.state = oldState;
    }

    public Vector3 GetCellWorldPos(Vector2Int cell)
    {
        if (mazeCells == null || cell.x < 0 || cell.x >= maze_x_size || cell.y < 0 || cell.y >= maze_z_size)
            return Vector3.zero;
        return mazeCells[cell.x, cell.y].transform.position;
    }

    public void SpawnPlayer(PlayerRef player)
    {
        if (Object.HasStateAuthority && !spawnedPlayers.ContainsKey(player))
        {
            Vector3 spawnPos = GetCellWorldPos(StartCell);
            spawnPos.y += 0.5f;

            NetworkObject playerObj = Runner.Spawn(playerPrefab, spawnPos, Quaternion.identity, player);
            spawnedPlayers.Add(player, playerObj);
        }
    }

    public void DespawnPlayer(PlayerRef player)
    {
        if (Object.HasStateAuthority && spawnedPlayers.TryGetValue(player, out NetworkObject playerObj))
        {
            if (playerObj != null)
                Runner.Despawn(playerObj);
            spawnedPlayers.Remove(player);
        }
    }

    // Keep your existing maze generation methods but use networked seed
    private void GenerateMaze()
    {
        GameObject newCell = mazeCellPrefab;

        // 1. Instantiate the cells
        for (int x = 0; x < maze_x_size; x++)
        {
            for (int z = 0; z < maze_z_size; z++)
            {
                Vector3 pos = new Vector3(x, 0, z);
                newCell = newCell == mazeCellPrefab ? mazeCellprefabSmall : mazeCellPrefab;
                GameObject cellObj = Instantiate(newCell, pos, Quaternion.identity, transform);
                MazeCell cell = cellObj.GetComponent<MazeCell>();
                mazeCells[x, z] = cell;
            }
        }

        // 2. Generate maze using existing algorithm
        int startX = UnityEngine.Random.Range(0, maze_x_size);
        int startZ = UnityEngine.Random.Range(0, maze_z_size);

        Stack<Vector2Int> stack = new Stack<Vector2Int>();
        Vector2Int current = new Vector2Int(startX, startZ);
        mazeCells[current.x, current.y].OnVisit();
        stack.Push(current);

        while (stack.Count > 0)
        {
            current = stack.Pop();
            List<Vector2Int> unvisitedNeighbors = GetUnvisitedNeighbors(current);
            if (unvisitedNeighbors.Count > 0)
            {
                stack.Push(current);
                Vector2Int next = unvisitedNeighbors[UnityEngine.Random.Range(0, unvisitedNeighbors.Count)];
                RemoveWalls(current, next);
                mazeCells[next.x, next.y].OnVisit();
                stack.Push(next);
            }
        }

        // 3. Set start and end cells
        if (Object.HasStateAuthority)
        {
            StartCell = new Vector2Int(UnityEngine.Random.Range(0, maze_x_size), 0);
            EndCell = new Vector2Int(UnityEngine.Random.Range(0, maze_x_size), maze_z_size - 1);
        }

        // 4. Place end trigger
        Vector3 endPos = mazeCells[EndCell.x, EndCell.y].transform.position;
        endPos.y += 0.5f;
        GameObject trigger = Instantiate(triggerPrefab, endPos, Quaternion.identity);

        // Add networked win trigger component
        NetworkedWinTrigger winTrigger = trigger.GetComponent<NetworkedWinTrigger>();
        if (winTrigger == null)
            winTrigger = trigger.AddComponent<NetworkedWinTrigger>();
    }

    // Keep your existing helper methods
    private List<Vector2Int> GetUnvisitedNeighbors(Vector2Int cell)
    {
        List<Vector2Int> neighbors = new List<Vector2Int>();

        if (cell.x > 0 && !mazeCells[cell.x - 1, cell.y].IsVisited)
            neighbors.Add(new Vector2Int(cell.x - 1, cell.y));
        if (cell.x < maze_x_size - 1 && !mazeCells[cell.x + 1, cell.y].IsVisited)
            neighbors.Add(new Vector2Int(cell.x + 1, cell.y));
        if (cell.y > 0 && !mazeCells[cell.x, cell.y - 1].IsVisited)
            neighbors.Add(new Vector2Int(cell.x, cell.y - 1));
        if (cell.y < maze_z_size - 1 && !mazeCells[cell.x, cell.y + 1].IsVisited)
            neighbors.Add(new Vector2Int(cell.x, cell.y + 1));

        return neighbors;
    }

    private void RemoveWalls(Vector2Int current, Vector2Int next)
    {
        int xDiff = next.x - current.x;
        int yDiff = next.y - current.y;

        if (xDiff == 1) // next is right
        {
            mazeCells[current.x, current.y].DeactivateWall(Direction.Right);
            mazeCells[next.x, next.y].DeactivateWall(Direction.Left);
        }
        else if (xDiff == -1) // next is left
        {
            mazeCells[current.x, current.y].DeactivateWall(Direction.Left);
            mazeCells[next.x, next.y].DeactivateWall(Direction.Right);
        }
        else if (yDiff == 1) // next is front
        {
            mazeCells[current.x, current.y].DeactivateWall(Direction.Frond);
            mazeCells[next.x, next.y].DeactivateWall(Direction.Back);
        }
        else if (yDiff == -1) // next is back
        {
            mazeCells[current.x, current.y].DeactivateWall(Direction.Back);
            mazeCells[next.x, next.y].DeactivateWall(Direction.Frond);
        }
    }

    // Keep other existing methods like GetRandomNeighborCell, GetWalkableNeighbors
    public Vector2Int GetRandomNeighborCell(Vector2Int current)
    {
        List<Vector2Int> open = new List<Vector2Int>();
        if (current.x > 0 && !mazeCells[current.x, current.y].HasWall(Direction.Left))
            open.Add(new Vector2Int(current.x - 1, current.y));
        if (current.x < maze_x_size - 1 && !mazeCells[current.x, current.y].HasWall(Direction.Right))
            open.Add(new Vector2Int(current.x + 1, current.y));
        if (current.y > 0 && !mazeCells[current.x, current.y].HasWall(Direction.Back))
            open.Add(new Vector2Int(current.x, current.y - 1));
        if (current.y < maze_z_size - 1 && !mazeCells[current.x, current.y].HasWall(Direction.Frond))
            open.Add(new Vector2Int(current.x, current.y + 1));

        if (open.Count == 0) return current;
        return open[UnityEngine.Random.Range(0, open.Count)];
    }

    public List<Vector2Int> GetWalkableNeighbors(Vector2Int cell)
    {
        List<Vector2Int> neighbors = new List<Vector2Int>();

        if (!mazeCells[cell.x, cell.y].HasWall(Direction.Right) && cell.x < maze_x_size - 1)
            neighbors.Add(new Vector2Int(cell.x + 1, cell.y));
        if (!mazeCells[cell.x, cell.y].HasWall(Direction.Left) && cell.x > 0)
            neighbors.Add(new Vector2Int(cell.x - 1, cell.y));
        if (!mazeCells[cell.x, cell.y].HasWall(Direction.Frond) && cell.y < maze_z_size - 1)
            neighbors.Add(new Vector2Int(cell.x, cell.y + 1));
        if (!mazeCells[cell.x, cell.y].HasWall(Direction.Back) && cell.y > 0)
            neighbors.Add(new Vector2Int(cell.x, cell.y - 1));

        return neighbors;
    }
}
